[package]
name = "poc_edge_client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message-io = "0.14"
serde = "1.0"
bincode = "1.3"
chrono = "0.4.19"
clap = { version = "2.33.3"}